name: CMake Build Action

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
            submodules: 'recursive'
    - uses: ashutoshvarma/setup-ninja@v1.1
    - uses: egor-tensin/setup-clang@v1

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "Ninja Multi-Config"
    - name: Build  
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
            submodules: 'recursive'
    - uses: egor-tensin/setup-clang@v1
    - name: Install libomp5 libomp-dev
      run: |
        sudo apt-get update; sudo apt-get install -y libomp5 libomp-dev
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
